<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GENIUS" name="testcases.TC001_Loginnegative" tests="4" failures="0" timestamp="23 Jul 2017 07:49:27 GMT" time="52.077" errors="1">
  <testcase name="loginLogOut" time="12.231" classname="testcases.TC001_Loginnegative"/>
  <testcase name="loginLogOut" time="14.598" classname="testcases.TC001_Loginnegative"/>
  <testcase name="loginLogOut" time="11.008" classname="testcases.TC001_Loginnegative"/>
  <testcase name="loginLogOut" time="14.240" classname="testcases.TC001_Loginnegative">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:33)
	at utils.Reporter.reportStep(Reporter.java:43)
	at wrappers.GenericWrappers.verifyTextContainsById(GenericWrappers.java:283)
	at pages.LoginPage.verifyLoginDetails(LoginPage.java:45)
	at testcases.TC001_Loginnegative.loginLogOut(TC001_Loginnegative.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loginLogOut -->
</testsuite> <!-- testcases.TC001_Loginnegative -->
